@startuml KitchenHatch

package de.thro.inf.prg3.a10.kitchen {
    +interface KitchenHatch {
        getMaxDishes(): int
        getOrderCount(): int
        getDishesCount(): int
        dequeueOrder(): Order
        dequeueOrder(timeout: long): Order
        dequeueDish(): Dish
        dequeueDish(timeout: long): Dish
        enqueueDish(dish: Dish)
    }

    +class KitchenHatchImpl implements KitchenHatch {
        +KitchenHatchImpl(maxMeals: int, orders: Deque<Order>)
    }
}

@enduml
